development:
  adapter: postgresql
  encoding: unicode
  database: development_new
  pool: 5


test:
  adapter: postgresql
  encoding: unicode
  database: test_new
  pool: 5
  
production:
  adapter: postgresql
  database: production_new
  pool: 5
  timeout: 5000

